// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendMessage.proto

package tutorial;

public final class SendMessage {
  private SendMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * <pre>
   *发送文件类型
   * </pre>
   *
   * Protobuf enum {@code tutorial.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>TEXT = 0;</code>
     */
    TEXT(0),
    /**
     * <code>IMAGE = 1;</code>
     */
    IMAGE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TEXT = 0;</code>
     */
    public static final int TEXT_VALUE = 0;
    /**
     * <code>IMAGE = 1;</code>
     */
    public static final int IMAGE_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return TEXT;
        case 1: return IMAGE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:tutorial.MessageType)
  }

  public interface FooOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Foo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *本机IP 来判断是否为本地发送的
     * </pre>
     *
     * <code>optional string ip = 2;</code>
     */
    java.lang.String getIp();
    /**
     * <pre>
     *本机IP 来判断是否为本地发送的
     * </pre>
     *
     * <code>optional string ip = 2;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>optional .tutorial.MessageType type = 3;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .tutorial.MessageType type = 3;</code>
     */
    tutorial.SendMessage.MessageType getType();

    /**
     * <pre>
     *发送内容
     * </pre>
     *
     * <code>optional bytes data = 4;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code tutorial.Foo}
   */
  public  static final class Foo extends
      com.google.protobuf.GeneratedMessageLite<
          Foo, Foo.Builder> implements
      // @@protoc_insertion_point(message_implements:tutorial.Foo)
      FooOrBuilder {
    private Foo() {
      name_ = "";
      ip_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.String name_;
    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    private void setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
    }
    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value.toStringUtf8();
    }

    public static final int IP_FIELD_NUMBER = 2;
    private java.lang.String ip_;
    /**
     * <pre>
     *本机IP 来判断是否为本地发送的
     * </pre>
     *
     * <code>optional string ip = 2;</code>
     */
    public java.lang.String getIp() {
      return ip_;
    }
    /**
     * <pre>
     *本机IP 来判断是否为本地发送的
     * </pre>
     *
     * <code>optional string ip = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(ip_);
    }
    /**
     * <pre>
     *本机IP 来判断是否为本地发送的
     * </pre>
     *
     * <code>optional string ip = 2;</code>
     */
    private void setIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ip_ = value;
    }
    /**
     * <pre>
     *本机IP 来判断是否为本地发送的
     * </pre>
     *
     * <code>optional string ip = 2;</code>
     */
    private void clearIp() {
      
      ip_ = getDefaultInstance().getIp();
    }
    /**
     * <pre>
     *本机IP 来判断是否为本地发送的
     * </pre>
     *
     * <code>optional string ip = 2;</code>
     */
    private void setIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ip_ = value.toStringUtf8();
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>optional .tutorial.MessageType type = 3;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .tutorial.MessageType type = 3;</code>
     */
    public tutorial.SendMessage.MessageType getType() {
      tutorial.SendMessage.MessageType result = tutorial.SendMessage.MessageType.forNumber(type_);
      return result == null ? tutorial.SendMessage.MessageType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .tutorial.MessageType type = 3;</code>
     */
    private void setTypeValue(int value) {
        type_ = value;
    }
    /**
     * <code>optional .tutorial.MessageType type = 3;</code>
     */
    private void setType(tutorial.SendMessage.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
    }
    /**
     * <code>optional .tutorial.MessageType type = 3;</code>
     */
    private void clearType() {
      
      type_ = 0;
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     *发送内容
     * </pre>
     *
     * <code>optional bytes data = 4;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <pre>
     *发送内容
     * </pre>
     *
     * <code>optional bytes data = 4;</code>
     */
    private void setData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      data_ = value;
    }
    /**
     * <pre>
     *发送内容
     * </pre>
     *
     * <code>optional bytes data = 4;</code>
     */
    private void clearData() {
      
      data_ = getDefaultInstance().getData();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!name_.isEmpty()) {
        output.writeString(1, getName());
      }
      if (!ip_.isEmpty()) {
        output.writeString(2, getIp());
      }
      if (type_ != tutorial.SendMessage.MessageType.TEXT.getNumber()) {
        output.writeEnum(3, type_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(4, data_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!name_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      if (!ip_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getIp());
      }
      if (type_ != tutorial.SendMessage.MessageType.TEXT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static tutorial.SendMessage.Foo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static tutorial.SendMessage.Foo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static tutorial.SendMessage.Foo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static tutorial.SendMessage.Foo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static tutorial.SendMessage.Foo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static tutorial.SendMessage.Foo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static tutorial.SendMessage.Foo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static tutorial.SendMessage.Foo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static tutorial.SendMessage.Foo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static tutorial.SendMessage.Foo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tutorial.SendMessage.Foo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code tutorial.Foo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          tutorial.SendMessage.Foo, Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Foo)
        tutorial.SendMessage.FooOrBuilder {
      // Construct using tutorial.SendMessage.Foo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <pre>
       *本机IP 来判断是否为本地发送的
       * </pre>
       *
       * <code>optional string ip = 2;</code>
       */
      public java.lang.String getIp() {
        return instance.getIp();
      }
      /**
       * <pre>
       *本机IP 来判断是否为本地发送的
       * </pre>
       *
       * <code>optional string ip = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        return instance.getIpBytes();
      }
      /**
       * <pre>
       *本机IP 来判断是否为本地发送的
       * </pre>
       *
       * <code>optional string ip = 2;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        copyOnWrite();
        instance.setIp(value);
        return this;
      }
      /**
       * <pre>
       *本机IP 来判断是否为本地发送的
       * </pre>
       *
       * <code>optional string ip = 2;</code>
       */
      public Builder clearIp() {
        copyOnWrite();
        instance.clearIp();
        return this;
      }
      /**
       * <pre>
       *本机IP 来判断是否为本地发送的
       * </pre>
       *
       * <code>optional string ip = 2;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIpBytes(value);
        return this;
      }

      /**
       * <code>optional .tutorial.MessageType type = 3;</code>
       */
      public int getTypeValue() {
        return instance.getTypeValue();
      }
      /**
       * <code>optional .tutorial.MessageType type = 3;</code>
       */
      public Builder setTypeValue(int value) {
        copyOnWrite();
        instance.setTypeValue(value);
        return this;
      }
      /**
       * <code>optional .tutorial.MessageType type = 3;</code>
       */
      public tutorial.SendMessage.MessageType getType() {
        return instance.getType();
      }
      /**
       * <code>optional .tutorial.MessageType type = 3;</code>
       */
      public Builder setType(tutorial.SendMessage.MessageType value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>optional .tutorial.MessageType type = 3;</code>
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      /**
       * <pre>
       *发送内容
       * </pre>
       *
       * <code>optional bytes data = 4;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return instance.getData();
      }
      /**
       * <pre>
       *发送内容
       * </pre>
       *
       * <code>optional bytes data = 4;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setData(value);
        return this;
      }
      /**
       * <pre>
       *发送内容
       * </pre>
       *
       * <code>optional bytes data = 4;</code>
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.Foo)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new tutorial.SendMessage.Foo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          tutorial.SendMessage.Foo other = (tutorial.SendMessage.Foo) arg1;
          name_ = visitor.visitString(!name_.isEmpty(), name_,
              !other.name_.isEmpty(), other.name_);
          ip_ = visitor.visitString(!ip_.isEmpty(), ip_,
              !other.ip_.isEmpty(), other.ip_);
          type_ = visitor.visitInt(type_ != 0, type_,    other.type_ != 0, other.type_);
          data_ = visitor.visitByteString(data_ != com.google.protobuf.ByteString.EMPTY, data_,
              other.data_ != com.google.protobuf.ByteString.EMPTY, other.data_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  name_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  ip_ = s;
                  break;
                }
                case 24: {
                  int rawValue = input.readEnum();

                  type_ = rawValue;
                  break;
                }
                case 34: {

                  data_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (tutorial.SendMessage.Foo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:tutorial.Foo)
    private static final tutorial.SendMessage.Foo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Foo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static tutorial.SendMessage.Foo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Foo> PARSER;

    public static com.google.protobuf.Parser<Foo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
